# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tabs App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bet Tracking App
pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Crashlytics'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'SVProgressHUD'
pod 'ChameleonFramework'

end
